openapi: 3.1.0
info:
    title: BookService API
    version: 1.0.0
paths:
    /api/book/v1/books:
        post:
            tags:
                - BookService
            summary: GetBooks
            description: GetSongs retrieves a list of songs with optional filtering and pagination
            operationId: GetBooks
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/GetBooksRequest'
                required: true
            responses:
                "200":
                    description: Successful response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetBooksResponse'
                default:
                    description: Error response
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                    code:
                                        type: integer
components:
    schemas:
        GetBooksRequest:
            type: object
            properties:
                bookIdList:
                    type: array
                    items:
                        $ref: '#/components/schemas/BookID'
                    maxItems: 50
                    minItems: 1
            description: Request message for getting books
        BookID:
            type: object
            properties:
                value:
                    type: string
                    examples:
                        - 550e8400-e29b-41d4-a716-446655440000
                        - f47ac10b-58cc-4372-a567-0e02b2c3d479
                        - 123e4567-e89b-12d3-a456-426614174000
                        - 6ba7b810-9dad-11d1-80b4-00c04fd430c8
                        - 6ba7b811-9dad-11d1-80b4-00c04fd430c8
                    format: uuid
                    description: UUID value for the song identifier
                    example: 550e8400-e29b-41d4-a716-446655440000
            description: BookID represents a typed identifier for songs
        GetBooksResponse:
            type: object
            properties:
                books:
                    type: array
                    items:
                        $ref: '#/components/schemas/Book'
            description: Response message for getting books
        Book:
            type: object
            properties:
                id:
                    $ref: '#/components/schemas/BookID'
                title:
                    $ref: '#/components/schemas/TranslatedString'
                releaseYear:
                    type: integer
                    examples:
                        - 1975
                        - 1976
                        - 1971
                    minimum: 1900
                    format: int32
                    description: Release year (optional)
                    example: 1975
            description: Book represents a book (no shit?)
        TranslatedString:
            type: object
            properties:
                translations:
                    type: array
                    items:
                        $ref: '#/components/schemas/Translation'
                    maxItems: 10
                    minItems: 1
            description: TranslatedString represents a string in multiple languages
        Translation:
            type: object
            properties:
                language:
                    type: string
                    enum:
                        - LANGUAGE_UNSPECIFIED
                        - LANGUAGE_ARABIC
                        - LANGUAGE_ENGLISH
                        - LANGUAGE_FRENCH
                        - LANGUAGE_SPANISH
                    description: Language represents supported languages in the system
                text:
                    type: string
                    examples:
                        - Bohemian Rhapsody
                        - رابسودي بوهيمي
                        - Rhapsodie bohémienne
                        - Rapsodia bohemia
                        - Hotel California
                        - فندق كاليفورنيا
                        - Hôtel California
                        - Hotel California
                    maxLength: 1000
                    minLength: 1
                    description: Translated text content
                    example: Bohemian Rhapsody
            description: Translation represents a single language translation
